nelmio_api_doc:
  documentation:
    info:
      title: Lilit test task
      description: Lilit test task documentation
      version: 1.0.0
  areas:
    path_patterns:
      - ^/api(?!/doc$)